IF DB_ID(N'TickeXDb') IS NULL CREATE DATABASE [TickeXDb];
IF DB_ID(N'TickeXHangfire') IS NULL CREATE DATABASE [TickeXHangfire];
GO

IF SUSER_ID(N'$(MSSQL_APP_USER)') IS NULL
    CREATE LOGIN [$(MSSQL_APP_USER)] WITH PASSWORD = N'$(MSSQL_APP_PASSWORD)', CHECK_POLICY = ON;
IF SUSER_ID(N'$(MSSQL_HANGFIRE_USER)') IS NULL
    CREATE LOGIN [$(MSSQL_HANGFIRE_USER)] WITH PASSWORD = N'$(MSSQL_HANGFIRE_PASSWORD)', CHECK_POLICY = ON;
IF SUSER_ID(N'$(MSSQL_MIGRATOR_USER)') IS NULL
    CREATE LOGIN [$(MSSQL_MIGRATOR_USER)] WITH PASSWORD = N'$(MSSQL_MIGRATOR_PASSWORD)', CHECK_POLICY = ON;
GO

USE [TickeXDb];
IF DATABASE_PRINCIPAL_ID(N'$(MSSQL_APP_USER)') IS NULL CREATE USER [$(MSSQL_APP_USER)] FOR LOGIN [$(MSSQL_APP_USER)];
IF DATABASE_PRINCIPAL_ID(N'$(MSSQL_MIGRATOR_USER)') IS NULL CREATE USER [$(MSSQL_MIGRATOR_USER)] FOR LOGIN [$(MSSQL_MIGRATOR_USER)];
IF IS_ROLEMEMBER(N'db_datareader', N'$(MSSQL_APP_USER)') <> 1 ALTER ROLE [db_datareader] ADD MEMBER [$(MSSQL_APP_USER)];
IF IS_ROLEMEMBER(N'db_datawriter', N'$(MSSQL_APP_USER)') <> 1 ALTER ROLE [db_datawriter] ADD MEMBER [$(MSSQL_APP_USER)];
IF IS_ROLEMEMBER(N'db_datareader', N'$(MSSQL_MIGRATOR_USER)') <> 1 ALTER ROLE [db_datareader] ADD MEMBER [$(MSSQL_MIGRATOR_USER)];
IF IS_ROLEMEMBER(N'db_datawriter', N'$(MSSQL_MIGRATOR_USER)') <> 1 ALTER ROLE [db_datawriter] ADD MEMBER [$(MSSQL_MIGRATOR_USER)];
IF IS_ROLEMEMBER(N'db_ddladmin', N'$(MSSQL_MIGRATOR_USER)') <> 1 ALTER ROLE [db_ddladmin] ADD MEMBER [$(MSSQL_MIGRATOR_USER)];
GO

USE [TickeXHangfire];
IF DATABASE_PRINCIPAL_ID(N'$(MSSQL_HANGFIRE_USER)') IS NULL CREATE USER [$(MSSQL_HANGFIRE_USER)] FOR LOGIN [$(MSSQL_HANGFIRE_USER)];
IF DATABASE_PRINCIPAL_ID(N'$(MSSQL_MIGRATOR_USER)') IS NULL CREATE USER [$(MSSQL_MIGRATOR_USER)] FOR LOGIN [$(MSSQL_MIGRATOR_USER)];
IF SCHEMA_ID(N'HangFire') IS NULL EXEC(N'CREATE SCHEMA [HangFire]');
IF IS_ROLEMEMBER(N'db_datareader', N'$(MSSQL_HANGFIRE_USER)') <> 1 ALTER ROLE [db_datareader] ADD MEMBER [$(MSSQL_HANGFIRE_USER)];
IF IS_ROLEMEMBER(N'db_datawriter', N'$(MSSQL_HANGFIRE_USER)') <> 1 ALTER ROLE [db_datawriter] ADD MEMBER [$(MSSQL_HANGFIRE_USER)];
GRANT CREATE TABLE TO [$(MSSQL_HANGFIRE_USER)];
GRANT ALTER ON SCHEMA::[HangFire] TO [$(MSSQL_HANGFIRE_USER)];
GRANT EXECUTE ON SCHEMA::[HangFire] TO [$(MSSQL_HANGFIRE_USER)];
IF IS_ROLEMEMBER(N'db_datareader', N'$(MSSQL_MIGRATOR_USER)') <> 1 ALTER ROLE [db_datareader] ADD MEMBER [$(MSSQL_MIGRATOR_USER)];
IF IS_ROLEMEMBER(N'db_datawriter', N'$(MSSQL_MIGRATOR_USER)') <> 1 ALTER ROLE [db_datawriter] ADD MEMBER [$(MSSQL_MIGRATOR_USER)];
IF IS_ROLEMEMBER(N'db_ddladmin', N'$(MSSQL_MIGRATOR_USER)') <> 1 ALTER ROLE [db_ddladmin] ADD MEMBER [$(MSSQL_MIGRATOR_USER)];
GO
