import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, RotateCcw } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import api from '../services/api';
import { Event } from '../types';
import { SkeletonCard } from '../components/Skeletons/SkeletonCard';
import { DiscoveryHero } from '../components/Discovery/DiscoveryHero';
import { EventCard } from '../components/Discovery/EventCard';
import { parseCatalogState, writeCatalogState } from '../utils/customerState';

export default function DashboardPage() {
  const [urlParams, setUrlParams] = useSearchParams();
  const initial = parseCatalogState(urlParams);
  const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false);
  const [search, setSearch] = useState(initial.search); const [selectedCategory, setSelectedCategory] = useState(initial.category); const [sortBy, setSortBy] = useState(initial.sort); const [page, setPage] = useState(initial.page); const [totalPages, setTotalPages] = useState(1); const [totalCount, setTotalCount] = useState(0); const [searchTrigger, setSearchTrigger] = useState(0);
  useEffect(() => { setUrlParams(writeCatalogState({ search, category: selectedCategory, sort: sortBy, page })); }, [page, searchTrigger, selectedCategory, sortBy, setUrlParams]);
  useEffect(() => { const next = parseCatalogState(urlParams); setSearch(next.search); setSelectedCategory(next.category); setSortBy(next.sort); setPage(next.page); }, [urlParams]);
  useEffect(() => {
    const controller = new AbortController(); let cancelled = false;
    (async () => { setLoading(true); setLoadError(false); try { const params = new URLSearchParams({ page: page.toString(), pageSize: '6', sortBy }); if (search.trim()) params.append('search', search.trim()); if (selectedCategory && selectedCategory !== 'All') params.append('category', selectedCategory); const response = await api.get(`/api/events?${params.toString()}`, { signal: controller.signal }); if (!cancelled && response.data.success) { setEvents(response.data.data.items || []); setTotalPages(response.data.data.totalPages || 1); setTotalCount(response.data.data.totalCount || 0); } else if (!cancelled) setLoadError(true); } catch (error: unknown) { if (!cancelled && (error as { name?: string })?.name !== 'CanceledError' && (error as { code?: string })?.code !== 'ERR_CANCELED') setLoadError(true); } finally { if (!cancelled) setLoading(false); } })();
    return () => { cancelled = true; controller.abort(); };
  }, [page, selectedCategory, sortBy, searchTrigger]);
  const resetFilters = () => { setSearch(''); setSelectedCategory('All'); setSortBy('date_asc'); setPage(1); setSearchTrigger((value) => value + 1); };
  const featuredEvent = events[0];
  return <div className="space-y-10 pb-16 text-text-primary"><DiscoveryHero search={search} sortBy={sortBy} selectedCategory={selectedCategory} onSearchChange={setSearch} onSortChange={(value) => { setSortBy(value); setPage(1); }} onCategoryChange={(value) => { setSelectedCategory(value); setPage(1); }} onSubmit={(event) => { event.preventDefault(); setPage(1); setSearchTrigger((value) => value + 1); }} />{featuredEvent && <EventCard event={featuredEvent} featured />}<section aria-labelledby="catalog-title" className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-border-subtle pb-4"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-brand-primary">Lịch sự kiện</p><h2 id="catalog-title" className="mt-1 text-2xl font-display font-bold text-text-primary sm:text-3xl">Khám phá chương trình</h2></div><p className="text-sm text-text-secondary">{events.length} / {totalCount} sự kiện</p></div>{loading ? <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">{[1, 2, 3, 4, 5, 6].map((item) => <SkeletonCard key={item} />)}</div> : loadError ? <StatePanel title="Không thể tải danh sách sự kiện" message="Kiểm tra kết nối rồi thử lại." actionLabel="Thử lại" onAction={() => setSearchTrigger((value) => value + 1)} /> : events.length === 0 ? <StatePanel title="Chưa có sự kiện phù hợp" message="Thử từ khóa hoặc danh mục khác." actionLabel="Đặt lại bộ lọc" onAction={resetFilters} /> : <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">{events.map((event) => <EventCard key={event.id} event={event} />)}</div>}{totalPages > 1 && <nav aria-label="Phân trang sự kiện" className="flex items-center justify-center gap-2 pt-4"><button type="button" aria-label="Trang trước" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={page === 1} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg border border-border-subtle bg-surface-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" aria-hidden="true" /></button><span className="px-3 text-sm text-text-secondary">Trang {page} / {totalPages}</span><button type="button" aria-label="Trang sau" onClick={() => setPage((value) => Math.min(totalPages, value + 1))} disabled={page === totalPages} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg border border-border-subtle bg-surface-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" aria-hidden="true" /></button></nav>}</section></div>;
}

function StatePanel({ title, message, actionLabel, onAction }: { title: string; message: string; actionLabel: string; onAction: () => void }) { return <div className="surface-panel flex flex-col items-center justify-center px-6 py-16 text-center"><RotateCcw className="mb-4 h-8 w-8 text-brand-primary" aria-hidden="true" /><h3 className="text-xl font-display font-bold text-text-primary">{title}</h3><p className="mt-2 text-base text-text-secondary">{message}</p><button type="button" onClick={onAction} className="mt-6 inline-flex min-h-11 items-center rounded-lg bg-brand-primary px-5 text-sm font-bold text-white hover:bg-brand-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary">{actionLabel}</button></div>; }
